# Generated by Django 6.0.3 on 2026-04-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
